self-hosted-runner:
  labels: []
  name: ""

runner-label:
  allow: []
  deny: ["@master", "@main"]

matrix:
  allow-empty: false
  max-dimensions: 16
  max-rows: 256

shell-name:
  disallow: []
  prefer: "bash"

workflow-call:
  inputs: []
  outputs: []
  secrets: []

# 禁用 config_file 输入参数检查
ignore:
  - "config_file"