[phases.setup]
nixPkgs = ["nodejs_20"]
# Force redeploy: 2025-10-23 08:52 UTC

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "cd services/planning-engine && npx prisma generate",
  "cd services/planning-engine && npm run build"
]

[start]
cmd = "node services/planning-engine/dist/index.js"
