[phases.setup]
nixPkgs = ["nodejs_20"]
# Force redeploy: 2025-10-23 13:42 UTC - workspace build fix

[phases.install]
cmds = ["npm ci --workspaces --include-workspace-root --include=dev --no-audit --no-fund"]

[phases.build]
cmds = ["npm run build:planning-engine", "ls -la services/planning-engine/dist || echo 'dist folder missing'"]

[start]
cmd = "node services/planning-engine/dist/index.js"
