[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["cd services/planning-engine && npm run build"]

[start]
cmd = "node services/planning-engine/dist/index.js"
