[phases.setup]
nixPkgs = ["nodejs_20"]
hotfix/docker-prisma-129
=======
hotfix/docker-prisma-129
=======
hotfix/docker-prisma-129
# Force redeploy: 2025-10-24 09:50 UTC - preserve build output
=======
# Force redeploy: 2025-10-24 09:35 UTC - add DATABASE_URL for prisma
main
main

[phases.install]
cmds = ["npm ci --workspaces --include-workspace-root --include=dev --no-audit --no-fund"]

[phases.build]
cmds = [
  "export DATABASE_URL=${DATABASE_URL:-postgresql://dummy:dummy@localhost:5432/dummy}",
  "npm run build:planning-engine",
hotfix/docker-prisma-129
  "ls -la services/planning-engine/dist && echo 'Build artifacts created' || echo 'ERROR: dist not found'"
]

[staticAssets]
=======
hotfix/docker-prisma-129
=======
hotfix/docker-prisma-129
main
  "ls -la services/planning-engine/dist && echo 'Build artifacts created' || echo 'ERROR: dist not found'"
]

# Prevent nixpacks from copying source again after build
[staticAssets]
hotfix/docker-prisma-129
=======
=======
  "ls -la services/planning-engine/dist || echo 'ERROR: dist not found'"
]
main

main

[start]
cmd = "node services/planning-engine/dist/index.js"
