[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm ci --workspaces --include-workspace-root --include=dev --no-audit --no-fund"]

[phases.build]
cmds = [
  "export DATABASE_URL=${DATABASE_URL:-postgresql://dummy:dummy@localhost:5432/dummy}",
  "npm run build:planning-engine",
  "ls -la services/planning-engine/dist && echo 'Build OK' || echo 'ERROR: dist not found'"
]

[staticAssets]

[start]
cmd = "node services/planning-engine/dist/index.js"
