[phases.setup]
nixPkgs = ["nodejs-20_x", "openssl"]

[phases.install]
cmds = ["npm ci --workspaces --include-workspace-root"]

[phases.build]
cmds = ["npm run build:planning-engine"]

[start]
cmd = "node services/planning-engine/dist/index.js"
