[build]
builder = "nixpacks"
buildCommand = "cd services/planning-engine && npm run build"
watchPatterns = ["services/planning-engine/**"]

[deploy]
startCommand = "cd services/planning-engine && node dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
