[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.planning-engine"

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
