[build]
builder = "dockerfile"
watchPatterns = ["services/planning-engine/**"]

[deploy]
startCommand = "npm run build:planning-engine && node services/planning-engine/dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
