[build]
fix/add-dockerfile
builder = "dockerfile"
=======
fix/add-dockerfile
builder = "dockerfile"
=======
builder = "nixpacks"
buildCommand = "npm run build:planning-engine"
main
watchPatterns = ["services/planning-engine/**"]

[deploy]
startCommand = "node services/planning-engine/dist/index.js"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
