id: stream-e-readiness-range
openapi: 3.0.0
info:
  title: Insights Readiness Range
  version: 1.0.0
paths:
  /api/v1/readiness/{userId}:
    get:
      summary: Get readiness range (descending by date)
      parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
        - in: query
          name: days
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 31
            default: 7
      responses:
        '200':
          description: Readiness items sorted by date DESC
          content:
            application/json:
              example:
                - userId: u1
                  date: '20240103'
                  score: 82
                  incomplete: false
                - userId: u1
                  date: '20240102'
                  score: 78
                  incomplete: false
        '500':
          description: Internal error
          content:
            application/json:
              example:
                error: internal_error
