version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: athlete-ally-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
      - redis_logs:/var/log/redis
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=YOUR_REDIS_PASSWORD
    networks:
      - athlete-ally-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: athlete-ally-redis-commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379:0:YOUR_REDIS_PASSWORD
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    networks:
      - athlete-ally-network
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data:
    driver: local
  redis_logs:
    driver: local

networks:
  athlete-ally-network:
    driver: bridge
