name: Artifact Suffix Reuse

on:
  workflow_call:
    inputs:
      matrix_mode:
        description: 'Matrix mode for artifact naming'
        required: false
        type: string
        default: 'na'
    outputs:
      artifact_suffix:
        description: 'Computed artifact suffix'
        value: ${{ github.run_id }}-${{ github.run_attempt }}-${{ github.job }}-${{ inputs.matrix_mode }}

jobs:
  compute-suffix:
    runs-on: ubuntu-latest
    outputs:
      artifact_suffix: ${{ steps.suffix.outputs.value }}
    steps:
      - name: Compute artifact suffix
        id: suffix
        run: |
          echo "value=${{ github.run_id }}-${{ github.run_attempt }}-${{ github.job }}-${{ inputs.matrix_mode }}" >> "$GITHUB_OUTPUT"
