name: Generate Prisma Clients

on:
  workflow_call:

jobs:
  generate-prisma:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.0'
          cache: 'npm'

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies


        run: npm ci --no-audit --no-fund
      - name: Generate Prisma clients
        run: |
          set -euo pipefail
          echo "🔧 Generating Prisma clients for all services..."
          # Use no-engine mode for reusable workflow (no DB runtime)
          export PRISMA_NO_ENGINE=1
          bash ./scripts/ci/prisma-generate.sh
          echo "✅ All Prisma clients generated"
