name: A2 Grafana Validator

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: a2-validator-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: Validate Grafana Dashboard A2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.0'
          cache: 'npm'

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Validate (skips when secrets missing)
        env:
          GRAFANA_URL: ${{ secrets.GRAFANA_URL }}
          GRAFANA_TOKEN: ${{ secrets.GRAFANA_TOKEN }}
          DASH_UID: aa-sleep-norm
        run: |
          node scripts/ops/a2-validate-grafana.mjs || true

      - name: Upload artifacts (7 days)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: a2-grafana-${{ github.run_id }}
          path: |
            reports/grafana/a2_validator_summary.json
            reports/grafana/*.png
          retention-days: 7