name: CI Diagnostics (npm ci)

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Align to .nvmrc
  NODE_VERSION: '20.18.0'
  NPM_VERSION: '10.9.3'

jobs:
  npm-ci-diagnostics:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Pin npm version
        run: |
          npm i -g "npm@${NPM_VERSION}"
          npm -v

      - name: Print environment
        run: |
          echo "Node: $(node -v)"
          echo "npm : $(npm -v)"
          echo "::group::npm config list -l"
          npm config list -l || true
          echo "::endgroup::"

      # ??1: ???????? (postinstall?)
      - name: npm ci (foreground scripts)
        id: ci_fg
        continue-on-error: true
        run: |
          set -o pipefail
          npm ci --foreground-scripts 2>&1 | tee npm-ci-foreground.log

      # ??2: ??????????????
      - name: npm ci (ignore scripts)
        id: ci_ign
        if: steps.ci_fg.outcome == 'failure'
        continue-on-error: true
        run: |
          set -o pipefail
          npm ci --ignore-scripts 2>&1 | tee npm-ci-ignore-scripts.log

      # ????????
      - name: Dump dependency tree
        run: |
          npm ls --all --json > npm-ls.json || true

      - name: Dedupe (dry-run)
        run: |
          # npm dedupe --dry-run ????npm 10???
          npm dedupe --dry-run 2>&1 | tee npm-dedupe-dry-run.log || true

      # ???? (??????)
      - name: npm audit (json)
        continue-on-error: true
        run: |
          npm audit --json > npm-audit.json || true

      # ??????????
      - name: Summarize diagnostics
        run: |
          {
            echo "Node: $(node -v)"
            echo "npm : $(npm -v)"
            echo "npm ci (foreground scripts): ${{ steps.ci_fg.outcome }}"
            if [ "${{ steps.ci_fg.outcome }}" = "failure" ]; then
              echo "npm ci (ignore scripts): ${{ steps.ci_ign.outcome }}"
            fi
          } | tee diagnostics-summary.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: npm-ci-diagnostics-${{ github.run_id }}
          path: |
            npm-ci-foreground.log
            npm-ci-ignore-scripts.log
            npm-ls.json
            npm-dedupe-dry-run.log
            npm-audit.json
            diagnostics-summary.txt
          retention-days: 14

      # ??: ??npm ci (foreground)???????
      - name: Build (only if npm ci succeeded)
        if: steps.ci_fg.outcome == 'success'
        run: |
          npm run build

