name: Frontend Harness Check (jsdom)

on:
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  harness:
    name: Frontend Single-Spec (PlanCard)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout (selected ref)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Sanity: print ref and verify lock contains jsdom env
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          echo "GITHUB_SHA=$GITHUB_SHA"
          git rev-parse --abbrev-ref HEAD
          git log -1 --oneline
          echo "=== Checking package-lock.json for jsdom dependencies ==="
          grep -q '"jest-environment-jsdom"' package-lock.json && echo "✅ Lock includes jest-environment-jsdom" || echo "❌ Lock missing jest-environment-jsdom"
          grep -q '"jsdom"' package-lock.json && echo "✅ Lock includes jsdom" || echo "❌ Lock missing jsdom"
          grep -q '"@types/jsdom"' package-lock.json && echo "✅ Lock includes @types/jsdom" || echo "❌ Lock missing @types/jsdom"

      - name: Discover lockfiles
        id: locks
        run: |
          echo "paths<<EOF" >> $GITHUB_OUTPUT
          git ls-files **/package-lock.json
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Setup Node 20 with npm cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ${{ steps.locks.outputs.paths }}

      - name: Clear npm cache and install dependencies
        run: |
          npm cache clean --force
          npm ci --legacy-peer-deps

      - name: Print Jest version
        run: npx jest --version

      - name: Run single frontend spec (jsdom)
        run: |
          npx jest apps/frontend/src/__tests__/components/PlanCard.test.tsx \
            --runInBand --verbose --detectOpenHandles --forceExit

