name: Supply Chain - License Compliance

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'

permissions:
  contents: read

jobs:
  license:
    name: Scan Licenses (report-only)
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      TZ: UTC
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.x'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Run license scan
        run: node scripts/ops/license-scan.mjs

      - name: Upload License artifacts
        uses: actions/upload-artifact@v4
        with:
          name: licenses-${{ github.run_id }}
          path: reports/licenses/**
          if-no-files-found: warn
          retention-days: 7

      - name: Job Summary
        if: always()
        run: |
          echo "## License scan artifacts" >> "$GITHUB_STEP_SUMMARY"
          echo "- Run ID: ${{ github.run_id }}" >> "$GITHUB_STEP_SUMMARY"
