name: Lockfile Guard (refresh & diff)

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

env:
  NODE_VERSION: '18.20.4'
  NPM_VERSION: '10.x'

jobs:
  lockfile-guard:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Pin npm version
        run: |
          npm i -g "npm@${NPM_VERSION}"
          node -v
          npm -v

      - name: Snapshot lockfile (before)
        run: |
          cp package-lock.json package-lock.json.before
          sha256sum package-lock.json.before | tee lockfile_before.sha

      - name: Refresh lockfile only
        run: |
          npm i --package-lock-only 2>&1 | tee npm-package-lock-only.log

      - name: Snapshot lockfile (after)
        run: |
          cp package-lock.json package-lock.json.after
          sha256sum package-lock.json.after | tee lockfile_after.sha
          diff -u package-lock.json.before package-lock.json.after > lockfile.diff || true

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lockfile-guard-${{ github.run_id }}
          path: |
            package-lock.json.before
            package-lock.json.after
            lockfile_before.sha
            lockfile_after.sha
            lockfile.diff
            npm-package-lock-only.log

      - name: Fail if lockfile changed
        run: |
          if [ -s lockfile.diff ]; then
            echo "Lockfile is out-of-date with package.json or overrides. Regenerate and commit the updated lockfile." >&2
            exit 1
          fi
          echo "Lockfile is up-to-date."

