name: Prisma Migration Guard

on:
  pull_request:
    paths:
      - 'services/**/prisma/**'
      - 'prisma/**'
  workflow_dispatch:

jobs:
  sanity:
    uses: ./.github/workflows/_sanity-reuse.yml

  prisma-migration-guard:
    runs-on: ubuntu-latest
    needs: [sanity]
    if: github.event_name == 'pull_request'
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db_${{ github.run_id }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.0'
          cache: 'npm'
          cache-dependency-path: ${{ needs.sanity.outputs.cache-dependency-path || 'package-lock.json' }}

      - name: Install dependencies


        run: npm ci --no-audit --no-fund
      - name: Wait for PostgreSQL
        run: |
          echo "⏳ Waiting for PostgreSQL to be ready..."
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          echo "✅ PostgreSQL is ready"

      - name: Check for Prisma schema changes
        run: |
          echo "🔍 Checking for Prisma schema changes..."
          
          # Check if any Prisma schema files were modified
          PRISMA_CHANGED=$(git diff --name-only HEAD~1 HEAD | grep -c -E '\.(prisma)$' || echo 0)
          
          if [ "$PRISMA_CHANGED" -gt 0 ]; then
            echo "📦 Prisma schema files were modified"
            echo "Modified files:"
            git diff --name-only HEAD~1 HEAD | grep -E '\.(prisma)$'
          else
            echo "ℹ️  No Prisma schema changes detected"
            exit 0
          fi

      - name: Test migration up
        run: |
          echo "🔄 Testing migration up..."
          
          # Find all Prisma schemas
          PRISMA_SCHEMAS=$(find . -name "schema.prisma" -not -path "./node_modules/*")
          
          for schema in $PRISMA_SCHEMAS; do
            echo "Testing schema: $schema"
            schema_dir=$(dirname "$schema")
            
            cd "$schema_dir"
            
            # Set up test database URL with unique DB name
            export DATABASE_URL="postgresql://postgres:postgres@localhost:5432/test_db_${{ github.run_id }}"
            
            # Generate Prisma client for migration guard
            service_dir=$(dirname "$schema_dir")
            bash "$GITHUB_WORKSPACE/scripts/ci/prisma-generate.sh" "$service_dir"
            
            # Test migration up (non-destructive)
            echo "Testing migration up for $schema_dir..."
            npx prisma migrate dev --name test_migration --create-only || echo "No new migrations to create"
            
            cd - > /dev/null
          done
          
          echo "✅ Migration up test completed"

      - name: Test migration down (rollback)
        run: |
          echo "🔄 Testing migration rollback..."
          
          # This is a simplified rollback test
          # In a real scenario, you'd want to test actual rollback scenarios
          echo "ℹ️  Rollback testing would be implemented here"
          echo "This is a placeholder for future rollback validation"

      - name: Non-blocking status
        run: |
          echo "ℹ️  This is a non-blocking check for now"
          echo "It will be promoted to blocking after monitoring a few successful runs"
          echo "Current status: Monitoring phase"

      - name: Cleanup
        if: always()
        run: |
          echo "🧹 Cleaning up test resources..."
          # Clean up any test databases or temporary files
