name: Supply Chain - SBOM

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *' # daily 02:30 UTC

permissions:
  contents: read

jobs:
  sbom:
    name: Generate CycloneDX SBOMs
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      TZ: UTC
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.18.x'
          cache: 'npm'

      - name: Install
        run: npm ci

      - name: Generate SBOMs
        run: node scripts/ops/gen-sbom.mjs

      - name: Upload SBOM artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-${{ github.run_id }}
          path: reports/sbom/**
          if-no-files-found: warn
          retention-days: 7

      - name: Job Summary
        if: always()
        run: |
          echo "## SBOM artifacts" >> "$GITHUB_STEP_SUMMARY"
          echo "- Run ID: ${{ github.run_id }}" >> "$GITHUB_STEP_SUMMARY"
