name: Supply Chain - Secrets Scan

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '30 2 * * *'

permissions:
  contents: read

jobs:
  gitleaks:
    name: Gitleaks (report-only)
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      TZ: UTC
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        # Pinned to commit for supply-chain safety (tag v2)
        uses: zricethezav/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7
        with:
          args: --redact --report-format json --report-path gitleaks.json

      - name: Upload Gitleaks artifact
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-${{ github.run_id }}
          path: gitleaks.json
          if-no-files-found: warn
          retention-days: 7

      - name: Job Summary
        if: always()
        run: |
          echo "## Gitleaks report (non-blocking)" >> "$GITHUB_STEP_SUMMARY"
          echo "- Run ID: ${{ github.run_id }}" >> "$GITHUB_STEP_SUMMARY"
