name: Test Manual Workflow

on:
  workflow_dispatch:
    inputs:
      test_input:
        description: 'Test input'
        required: false
        default: 'test'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test step
        run: echo "Test workflow triggered with input: ${{ inputs.test_input }}"
